"""
Module 5 — Maritime Memory & Virtual Gateways Engine
Comprehensive export of all Phase 2 and Phase 3 core modules and innovation layers.
"""

from src.ais.audit import (
    GENESIS_HASH,
    MerkleAuditEngine,
    build_merkle_root,
    canonical_json,
    compute_row_hash,
)
from src.ais.behaviour import (
    BehaviourAuditor,
    BehaviourClassifier,
    EnvironmentalAdapter,
    WeatherProvider,
)
from src.ais.collective import CollectiveAnomalyDetector
from src.ais.crossing import CrossingDetector
from src.ais.dark_path import DarkPathReconstructor, OceanCurrentProvider
from src.ais.delay_analysis import DelayAnalyzer
from src.ais.dna import BehavioralDNAExtractor
from src.ais.gateways import (
    GatewayManager,
    gateways_to_geojson,
    get_default_gateways,
    get_gateway_manager,
)
from src.ais.ingest import (
    AisSource,
    CsvReplaySource,
    LiveFeedSource,
    get_default_adapter,
    get_default_source,
)
from src.ais.maritime_memory import MaritimeMemory
from src.ais.schemas import (
    AISContinuity,
    AISSourceMode,
    AisGap,
    AisPing,
    AisSourceMode,
    AuditAnchor,
    AuditVerifyResult,
    BaseEnvelope,
    BehaviourAssessment,
    BehaviourStatus,
    CandidateDarkPath,
    CollectiveAnomalyEvent,
    CollectiveAnomalyType,
    DarkPathHypothesis,
    DelayExplanation,
    DnaMatch,
    EvidenceBundleV1,
    EventType,
    ExpectedTimeBasis,
    ExplanationFactor,
    FactorSupportStatus,
    GatewayCorridor,
    GatewayCrossingEvent,
    JourneyStatus,
    ReplaySnapshot,
    RunManifest,
    SourceInfo,
    TrafficDensityBin,
    TrafficLevel,
    TransitAnalysis,
    VesselBehavioralDNA,
    VesselJourney,
    VesselTrack,
    nav_status_label,
)
from src.ais.track_builder import (
    WGS84_GEOD,
    TrackBuilder,
    geodesic_distance_km,
    geodesic_distance_nm,
)
from src.ais.traffic import TrafficAnalyzer

__all__ = [
    "AISContinuity",
    "AisGap",
    "AisPing",
    "AisSource",
    "AisSourceMode",
    "AuditAnchor",
    "AuditVerifyResult",
    "BaseEnvelope",
    "BehaviourAssessment",
    "BehaviourAuditor",
    "BehaviourClassifier",
    "BehaviourStatus",
    "BehavioralDNAExtractor",
    "CandidateDarkPath",
    "CollectiveAnomalyDetector",
    "CollectiveAnomalyEvent",
    "CollectiveAnomalyType",
    "CrossingDetector",
    "CsvReplaySource",
    "DarkPathHypothesis",
    "DarkPathReconstructor",
    "DelayAnalyzer",
    "DelayExplanation",
    "DnaMatch",
    "EvidenceBundleV1",
    "EventType",
    "ExpectedTimeBasis",
    "ExplanationFactor",
    "FactorSupportStatus",
    "GENESIS_HASH",
    "GatewayCorridor",
    "GatewayCrossingEvent",
    "GatewayManager",
    "JourneyStatus",
    "LiveFeedSource",
    "MaritimeMemory",
    "MerkleAuditEngine",
    "OceanCurrentProvider",
    "ReplaySnapshot",
    "RunManifest",
    "SourceInfo",
    "TrackBuilder",
    "TrafficAnalyzer",
    "TrafficDensityBin",
    "TrafficLevel",
    "TransitAnalysis",
    "VesselBehavioralDNA",
    "VesselJourney",
    "VesselTrack",
    "WGS84_GEOD",
    "WeatherProvider",
    "build_merkle_root",
    "canonical_json",
    "compute_row_hash",
    "gateways_to_geojson",
    "geodesic_distance_km",
    "geodesic_distance_nm",
    "get_default_adapter",
    "get_default_gateways",
    "get_default_source",
    "get_gateway_manager",
    "nav_status_label",
]
