"""
Module 7 — Counterfactual Trajectory Reasoning — Data Contracts

All types consumed and emitted by Module 7 are defined here.
No other Module 7 file may define public data structures.

FORENSIC BOUNDARY:
    This module produces *physical-consistency evidence*, not a probability of
    guilt, causal attribution, or accusation. The schema intentionally contains
    no field named 'culprit', 'responsible_vessel', 'guilt_probability', or
    any equivalent.

schema_version must be incremented on any breaking field change.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


MODULE7_SCHEMA_VERSION = "1.0.0"


# ── Enums ─────────────────────────────────────────────────────────────────────

class ReleaseSource(str, Enum):
    """Provenance of the hypothetical release location.

    AIS_OBSERVED
        Position taken directly from a recorded AIS ping at or near the release
        time. Highest positional confidence.

    DARK_PATH_RECONSTRUCTED
        Position generated by Module 6 during an AIS blackout using physics-
        informed dark-path reconstruction. Higher uncertainty than observed.
        All downstream comparisons that use this source must carry an explicit
        disclaimer.

    ORIGIN_ZONE_SAMPLE
        Position sampled uniformly from the Module 4 probable origin zone.
        Used exclusively for the null/background baseline; never attributed to
        a specific vessel.
    """
    AIS_OBSERVED = "AIS_OBSERVED"
    DARK_PATH_RECONSTRUCTED = "DARK_PATH_RECONSTRUCTED"
    ORIGIN_ZONE_SAMPLE = "ORIGIN_ZONE_SAMPLE"


class ReleaseMode(str, Enum):
    """Oil release model.

    POINT
        All oil enters the ocean at a single location and instant.
        Implemented in Phase 1.

    PATH
        Oil is released over a short duration as the vessel moves along its
        track. Not implemented until POINT has been fully validated (Phase 2).
    """
    POINT = "POINT"
    PATH = "PATH"


# ── Hypothesis ────────────────────────────────────────────────────────────────

@dataclass
class ReleaseLocation:
    """Geographic release point with provenance."""
    lat: float
    lon: float
    source: ReleaseSource
    # Optional human-readable note (e.g., gap_id, hypothesis_id from M6)
    note: str = ""


@dataclass
class CounterfactualHypothesis:
    """One testable counterfactual.

    Represents the statement:
        "If vessel <vessel_id> released oil at <location> at <release_time>,
         under environment version <environment_version>, would the resulting
         simulated spill resemble the observed SAR spill?"

    The hypothesis is either accepted or not *physically consistent* —
    never 'proven' or 'disproven'.
    """
    hypothesis_id: str                   # CF-{vessel_id}-T{ti:02d}-P{pi:02d}
    vessel_id: str
    release_time_iso: str                # ISO-8601 UTC
    release_location: ReleaseLocation
    release_mode: ReleaseMode
    environment_version: str             # tag for the VelocityField snapshot used
    particle_count: int
    ensemble_members: int


# ── Physical Metrics ──────────────────────────────────────────────────────────

@dataclass
class PhysicalMetrics:
    """Multi-metric spatial comparison between simulated and observed spills.

    All similarity values are in [0, 1]:
        1.0 → perfect agreement
        0.0 → maximum disagreement

    composite_score is a weighted sum of the individual metrics.
    The weights are read from config/counterfactual.yaml and must sum to 1.
    """
    iou: float                          # |A∩B| / |A∪B|
    centroid_similarity: float          # exp(-d / D), D = centroid_decay_km
    area_similarity: float              # 1 - |As - Ao| / max(As, Ao)
    shape_similarity: float             # exp(-hausdorff / H), H = hausdorff_decay_km
    orientation_similarity: float       # 1 - Δθ_axial / 90°  (axial PCA angle)
    composite_score: float              # weighted sum per config weights

    # Raster diagnostics
    observed_area_km2: float
    simulated_area_km2: float
    centroid_distance_km: float
    hausdorff_distance_km: float
    orientation_delta_deg: float        # axial angle difference (0–90°)


# ── Ensemble Result ───────────────────────────────────────────────────────────

@dataclass
class EnsembleResult:
    """Aggregated metrics across all ensemble members for one hypothesis."""
    hypothesis_id: str
    member_scores: List[float]          # composite_score per ensemble member
    mean_metrics: PhysicalMetrics       # mean over members


# ── Baseline ──────────────────────────────────────────────────────────────────

@dataclass
class BaselineStats:
    """Statistical distribution of physical match scores from null hypotheses.

    Null hypotheses are sampled uniformly from the Module 4 probable origin
    zone. They use identical physics, particle count, and uncertainty treatment
    to candidate simulations.

    The baseline lets analysts answer:
        "Does this candidate counterfactual outperform generic feasible
         source locations?"
    """
    n_samples: int
    median_score: float
    p25_score: float
    p75_score: float
    p95_score: float
    min_score: float
    max_score: float


# ── Time Sensitivity ──────────────────────────────────────────────────────────

@dataclass
class TimeSensitivity:
    """Physical match scores at time-shifted release hypotheses.

    Tests whether the match is specifically associated with the estimated
    release window rather than simply with the vessel being nearby.

    best_offset_hours may not be 0 — that result is informative, not masked.
    """
    offsets_hours: List[float]          # e.g., [-12, -6, 0, 6, 12]
    scores: Dict[float, float]          # offset_hours → composite_score
    best_offset_hours: float


# ── Candidate Selection ───────────────────────────────────────────────────────

@dataclass
class CandidateSelectionRecord:
    """Records why a vessel was included or excluded from Module 7 processing."""
    vessel_id: str
    eligible: bool
    temporal_reason: str                # e.g., TRACK_OVERLAPS_RELEASE_WINDOW
    spatial_reason: str                 # e.g., DARK_PATH_INTERSECTS_ORIGIN_ZONE
    exclusion_reason: Optional[str] = None  # populated only when eligible=False


# ── Evidence Bundle ───────────────────────────────────────────────────────────

@dataclass
class BestHypothesisSummary:
    """Concise summary of the highest-scoring counterfactual for one vessel."""
    hypothesis_id: str
    release_time_iso: str
    release_location: ReleaseLocation
    release_mode: ReleaseMode
    ensemble_member_count: int
    physical_metrics: PhysicalMetrics


@dataclass
class CounterfactualEvidenceBundleV1:
    """
    Frozen output contract for Module 7.

    Consumed by Module 8 (Investigation Priority) and reporting.
    schema_version must be bumped on any breaking change.

    FORENSIC BOUNDARY: This bundle establishes *physical consistency evidence*.
    It does NOT establish causation, guilt, intent, or a probability of
    responsibility. Every consumer of this bundle must treat the
    'interpretation' and 'limitations' fields as mandatory disclosures.
    """
    schema_version: str
    case_id: str
    vessel_id: str
    module7_version: str

    # Candidate selection traceability
    selection_record: CandidateSelectionRecord

    # All hypotheses tested
    hypotheses_tested: int

    # Best hypothesis
    best_hypothesis: Optional[BestHypothesisSummary]

    # Baseline comparison
    baseline: Optional[BaselineStats]

    # Candidate exceeds baseline p95?
    candidate_exceeds_p95: Optional[bool]

    # Time-shift sensitivity
    time_sensitivity: Optional[TimeSensitivity]

    # Mandatory human-readable interpretation and limitations
    interpretation: str
    limitations: List[str]

    # Provenance
    environment_version: str
    generated_at: str
