import sys; sys.path.insert(0,'src')
from PIL import Image
import numpy as np
from config import CASES, DATA_PROCESSED

SEEDS = {"case_01": 7, "case_02": 13, "case_03": 42}
PATCHES = {"case_01": 1, "case_02": 1, "case_03": 2}

print("=== SAR PNG Provenance Audit ===\n")
for cid, c in CASES.items():
    sar = Image.open(c['sar_image'])
    msk = Image.open(c['sar_mask'])
    msk_arr = np.array(msk)
    total_px = msk_arr.shape[0] * msk_arr.shape[1]
    spill_px = int((msk_arr > 127).sum())
    spill_pct = spill_px / total_px * 100
    bbox = c['spill_bbox']
    geo_h = (bbox['lat_max'] - bbox['lat_min']) * 111.32
    geo_w = (bbox['lon_max'] - bbox['lon_min']) * 111.32

    print(f"  {cid}")
    print(f"    Generated by    : generate_synthetic_data.py  seed={SEEDS[cid]}  n_patches={PATCHES[cid]}")
    print(f"    SAR image size  : {sar.size}  mode={sar.mode}  (NATIVE synthetic, NOT resized from Sentinel-1)")
    print(f"    Mask size       : {msk.size}  mode={msk.mode}")
    print(f"    Image = bbox?   : YES — 512x512 image WAS generated to represent the full bbox scene")
    print(f"    Config bbox     : {geo_h:.1f} km x {geo_w:.1f} km")
    print(f"    NATIVE m/px     : {geo_h*1000/sar.size[1]:.1f} m/px (lat)  {geo_w*1000/sar.size[0]:.1f} m/px (lon)  at 512x512")
    print(f"    After 256x256   : {geo_h*1000/256:.1f} m/px (lat)  {geo_w*1000/256:.1f} m/px (lon)  at 256x256")
    print(f"    Spill pixels    : {spill_px} / {total_px} ({spill_pct:.1f}% of image)")
    area_at_native = spill_px * (geo_h*1000/512) * (geo_w*1000/512) / 1e6
    print(f"    Area at 512x512 : {area_at_native:.1f} km2  (each pixel = {geo_h*1000/512:.0f}x{geo_w*1000/512:.0f} m)")
    print()

print("=== SegFormer input pipeline ===")
print("  Module 1 resizes both SAR and mask to 256x256 before inference")
print("  -> The 256x256 pred_mask.npy is a downsample of the 512x512 native image")
print("  -> GeoTransform must account for this: use (bbox / 256), NOT (bbox / 512)")
print("  -> This is what geo_transform.py already does (image_h=256, image_w=256)")
print()
print("=== Area verdict ===")
for cid, c in CASES.items():
    msk = Image.open(c['sar_mask']).resize((256,256), Image.NEAREST)
    msk_arr = np.array(msk)
    spill_px_256 = int((msk_arr > 127).sum())
    bbox = c['spill_bbox']
    geo_h = (bbox['lat_max'] - bbox['lat_min']) * 111.32
    geo_w = (bbox['lon_max'] - bbox['lon_min']) * 111.32
    m_per_px_lat = geo_h*1000/256
    m_per_px_lon = geo_w*1000/256
    area_km2 = spill_px_256 * m_per_px_lat * m_per_px_lon / 1e6
    area_pct = spill_px_256 / (256*256) * 100
    print(f"  {cid}: {spill_px_256} px at 256x256 = {area_km2:.1f} km2 ({area_pct:.1f}% of scene)")

print()
print("Note: The spill ellipses are small patches WITHIN the large scene.")
print("      A spill covering ~42k/66k pixels of a 512x512 scene that represents")
print("      ~170-190 km geographic extent is physically implausible for an oil spill.")
print("      CONCLUSION: the bbox does NOT represent the physical extent of the spill patch,")
print("      it represents the MONITORING SCENE. The spill is a localised patch within it.")
